name: 🦆 Build Ducky VPN APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    name: Ощипываем исходники и собираем APK
    runs-on: ubuntu-latest

    steps:
      - name: 🛠 Настройка Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 📥 Клонирование топового ядра (v2rayNG)
        run: git clone --depth 1 https://github.com/2dust/v2rayNG.git .

      - name: 🧬 Генная инженерия (Ребрендинг в Ducky VPN)
        run: |
          # Переходим внутрь папки с Android-проектом
          cd V2rayNG
          
          # Меняем название приложения на Ducky VPN
          sed -i 's/<string name="app_name">v2rayNG<\/string>/<string name="app_name">Ducky VPN<\/string>/g' app/src/main/res/values/strings.xml
          
      - name: ⚙️ Выдача прав сборщику Gradle
        run: |
          cd V2rayNG
          chmod +x ./gradlew

      - name: 🏗 Сборка APK (Debug-версия)
        run: |
          cd V2rayNG
          ./gradlew assembleDebug --no-daemon

      - name: 📦 Выгрузка готового файла
        uses: actions/upload-artifact@v4
        with:
          name: 🦆 Ducky-VPN-App
          # Обновлен путь для поиска собранного APK файла
          path: V2rayNG/app/build/outputs/apk/debug/*.apk
